/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controler.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ngohoa
 */
public class V_Tra extends javax.swing.JFrame {

    /**
     * Creates new form V_Tra
     */
    C_DATA data;
    C_ItemThietBi itemSelected;
    public V_Tra(C_DATA data) {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        this.data=data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Xác nhận");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Làm lại");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("Người trả");

        jTextField2.setEnabled(false);

        jTextField3.setEnabled(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mã tài sản");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Số hiệu máy");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        if(jTextField2.isEnabled()==false) jTextField2.setEnabled(true);
        if(jTextField3.isEnabled()==true) jTextField3.setEnabled(false);
        jTextField3.setText(null);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        if(jTextField3.isEnabled()==false) jTextField3.setEnabled(true);
        if(jTextField2.isEnabled()==true) jTextField2.setEnabled(false);
        jTextField2.setText(null);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(jTextField1.getText()==null||jTextField1.getText().equals("")) JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin","Lỗi", JOptionPane.WARNING_MESSAGE);
        else if(jTextField2.isEnabled()==false&&jTextField3.isEnabled()==false) JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin","Lỗi", JOptionPane.WARNING_MESSAGE);
        else if(jRadioButton1.isSelected()==true&&(jTextField2.getText()==null||jTextField2.getText().equals(""))) JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin","Lỗi", JOptionPane.WARNING_MESSAGE);
        else if(jRadioButton2.isSelected()==true&&(jTextField3.getText()==null||jTextField3.getText().equals(""))) JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin","Lỗi", JOptionPane.WARNING_MESSAGE);
        else if((jTextField2.getText()==null||jTextField2.getText().equals(""))&&(jTextField3.getText()==null||jTextField3.getText().equals("")))
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin","Lỗi", JOptionPane.WARNING_MESSAGE);
        else{
            if(jRadioButton1.isSelected()){
                itemSelected=data.timItemtheoMaTaiSan(jTextField2.getText());     
            }else{
                itemSelected=data.timItemtheoSoHieuMay(jTextField3.getText());
            }
            if(itemSelected==null)JOptionPane.showMessageDialog(null,"Không có thiết bị này","Lỗi", JOptionPane.WARNING_MESSAGE);
            else if(itemSelected.muonTra.tenNguoiMuon==null||itemSelected.muonTra.tenNguoiMuon.equals(""))JOptionPane.showMessageDialog(null,"Thiết bị này chưa có ai mượn","Lỗi", JOptionPane.WARNING_MESSAGE);
            else if(itemSelected.muonTra.tenNguoiMuon.equals(jTextField1.getText())==false) JOptionPane.showMessageDialog(null,"Tên người mượn thiết bị không hợp với tên người trả","Lỗi", JOptionPane.WARNING_MESSAGE);
            else{
                itemSelected.muonTra= new C_muonTra();
                //use quanlythietbi; DELETE FROM MuonTra WHERE MaTaiSan='1';
                String q = new String("use quanlythietbi; DELETE FROM MuonTra WHERE MaTaiSan='");
                String querry= q.concat(itemSelected.maTaiSan).concat("'");
                data.addquerry(querry);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
